services:
  - type: web
    name: gameon-backend
    env: node
    # Keep rootDir for clarity, but also prefix commands to be explicit
    rootDir: gameon-backend
    buildCommand: npm ci --prefix gameon-backend
    startCommand: npm start --prefix gameon-backend
    autoDeploy: true
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/gameon-backend/uploads
        sizeGB: 1